---
title: "Data Analysis"
subtitle: "The 3rd section"
author: "Yangyong Ye"
institute: "SOE, RUC"
date: "2020/12/22 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# estimation and inference


---

# model diagnostics

---
# results reports


---

???
2020年12，28日，最后一节课的反思
本来打算可以讲chapter 12- 15章的，还可以举一个从起点到终点完整量化分析的例子，但是时间还是不够。才讲到15章，即使15章的内容也只是粗略而过。具体而言，本身课程内容安排过多，另外一个原因在于学生的数理基础太薄弱，把一个概念讲明白花的时间远超出预期。

关于这本课程的内容选择与编排模式需要调整。现在所能想到的是要做以下两个方面的调整：当数据清理的内容放在图表之后。图表部分的内容，也并不以讲图表为内容，而是以exploratory data analysis 为主题来架构内容。因为图表的制作主要是进行探索性的分析。
第二个需要改进的部分，加入部分数理统计知识的讲解，比如说参数估计与假设检验的推导等等。

然后我忽然想到的一个问题：我们为什么学习量化研究方法，我们为什么要学习数理统计知识？当然这不仅仅是说我们学了这些知识和技术就可以去做量化研究，去写相反的论文。而是具有数据统计知识的人，它如果影响我们对世界的预设与看世界的方式。比较有些基本的预设：客观的世界的要素是关联在一起的。科研的重要使命是探究因果。误差是永远存在的，我们只是接近真理，而浊掌控他。

在思维方式，量化研究的三个重要特征是：可测量，相关性，事实性判断。即量化研究关注可测量，可用数字表达的现象，量化研究也会涉及单个特征的描述，但是更为核心的是进行不同要素之间相互关系的研究。量化研究的第三个特征，是它始终坚持的事实判断的视角。它很少去研究价值问题。价值问题会影响量化研究问题的选择。但价值选择的问题并不会成为量化研究的对象。
